version: 2
updates:
  - package-ecosystem: npm
    directory: "/"
    schedule:
      interval: "daily"
      time: "15:00"
    commit-message:
      prefix: "chore"
      prefix-development: "dev"
      include: "scope"
    labels:
      - "dependencies"
    open-pull-requests-limit: 10
    pull-request-branch-name:
      separator: "-"
    rebase-strategy: "auto"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    commit-message:
      prefix: "ci"
      include: "scope"
    labels:
      - "dependencies"
    open-pull-requests-limit: 10
    pull-request-branch-name:
      separator: "-"
    rebase-strategy: "auto"
